// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/candace-server/pkg/candaceos/harness (interfaces: Host)
//
// Generated by this command:
//
//	mockgen -destination=mock_host_test.go -package=externalconsumer_test github.com/candace-server/pkg/candaceos/harness Host
//

// Package externalconsumer_test is a generated GoMock package.
package externalconsumer_test

import (
	context "context"
	reflect "reflect"

	candaceosv1 "github.com/candace-server/proto/candace/candaceos/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockHost is a mock of Host interface.
type MockHost struct {
	ctrl     *gomock.Controller
	recorder *MockHostMockRecorder
	isgomock struct{}
}

// MockHostMockRecorder is the mock recorder for MockHost.
type MockHostMockRecorder struct {
	mock *MockHost
}

// NewMockHost creates a new mock instance.
func NewMockHost(ctrl *gomock.Controller) *MockHost {
	mock := &MockHost{ctrl: ctrl}
	mock.recorder = &MockHostMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHost) EXPECT() *MockHostMockRecorder {
	return m.recorder
}

// FleetStatus mocks base method.
func (m *MockHost) FleetStatus(ctx context.Context) (*candaceosv1.HarnessFleetStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FleetStatus", ctx)
	ret0, _ := ret[0].(*candaceosv1.HarnessFleetStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FleetStatus indicates an expected call of FleetStatus.
func (mr *MockHostMockRecorder) FleetStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FleetStatus", reflect.TypeOf((*MockHost)(nil).FleetStatus), ctx)
}

// Publish mocks base method.
func (m *MockHost) Publish(ctx context.Context, event *candaceosv1.HarnessEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockHostMockRecorder) Publish(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockHost)(nil).Publish), ctx, event)
}

// Reconcile mocks base method.
func (m *MockHost) Reconcile(ctx context.Context, request *candaceosv1.HarnessReconcileRequest) (*candaceosv1.ReconcileEvidence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", ctx, request)
	ret0, _ := ret[0].(*candaceosv1.ReconcileEvidence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockHostMockRecorder) Reconcile(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockHost)(nil).Reconcile), ctx, request)
}
